dist: bionic

cache:
  npm: true
  directories:
    - /home/travis/.volta

env:
  - CI=true

before_install:
  - curl https://get.volta.sh | bash
  - export VOLTA_HOME=$HOME/.volta
  - export PATH=$VOLTA_HOME:$PATH

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint --if-present
  - yarn test
  - yarn build --if-present
